### ISSUE TITLE
Outdated ActiveModel dependency

### ISSUE THREAD

**Issue by karmi** [maccman/supermodel#17]
Hi, Supermodel currently depends on ActiveModel 3.0. I'm using Supermodel as a "generic activemodel implementation" in http://github.com/karmi/tire and it's making it a bit painful, since the version is long outdated... Could Supermodel be upgraded to ActiveModel 3.2.x?

Thanks!,

Karel

**Comment by maccman** [comment]
Sure, pull requests are always welcome :)
