### ISSUE TITLE
If SuperModel support relationships? like belong_to or has_many.

### ISSUE THREAD

**Issue by shaoyangyu** [maccman/supermodel#20]
Hi

Not sure if SuperModel supoort relationships, like belong_to or has_many.

class Person
   has_many:addresses
end
.....
person.addresses = [ address ]
person.addresses.target #=> returns [ address ]
person.addresses.base #=> returns person
person.addresses.metadata #=> returns the metadata
.....

**Comment by FOMNick** [comment]
Yes, I'm using belongs_to in a Supermodel model in my project with great success. The readme is pretty light, so I recommend [checking the RDoc](http://rdoc.info/github/maccman/supermodel/master/frames) for such things.

**Comment by shaoyangyu** [comment]
thanks ~
