### ISSUE TITLE
activesupport 3.2.3 not supported

### ISSUE THREAD

**Issue by hbarrington** [maccman/supermodel#22]
you require inheritable_attributes and attr_accessor_with_default from active support's core extensions but those are no longer available in 3.2.3 (at least as far as i can tell)

**Comment by maccman** [comment]
Pull requests always accepted :)

**Comment by hbarrington** [comment]
looks to be fixed in head. although you're still using ActiveSupport::SecureRandom rather than SecureRandom. I'll open a new issue if you think it's appropriate

**Comment by hbarrington** [comment]
just saw there's already an issue
