### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ghost** [maccman/supermodel#5]
Attempting to create the follwing results in:

```
class Test < SuperModel::Redis
  attributes :name
  indexes :name
end

Test.find_or_create_by_name("foo")
```

TypeError: wrong argument type Module (expected Class)

Unless I'm missing something, this should be:

```
class Test < SuperModel::Base
  include SuperModel::Redis::Model
  attributes :name
  indexes :name
end

Test.find_or_create_by_name("foo")
```

**Comment by maccman** [comment]
Yes, you're absolutely correct - I've fixed it in the README - thanks!
